#!/usr/bin/env python3
"""Run the whole dossier, start to finish, on this machine.

    uv run python main.py                 # the real case, reusing what exists
    uv run python main.py --fresh         # discard the analysis and redo it
    uv run python main.py --rebuild       # also re-read the PDFs (costs money)

Defaults to the real case (`private`) and to local adjudication, because that is
what this is for. Nothing here reaches the network except the cloud stages of a
`--rebuild`, and nothing is ever pushed.

**The two kinds of "fresh" are not the same, and conflating them is expensive.**

`--fresh` throws away the *analysis*: findings, the verification cache, the
digest, the report, and any pending obligation proposal. All of it is
regenerated by the local model, so it costs time and electricity and nothing
else. This is the one you want when the catalog or the engine changed.

`--rebuild` additionally re-runs the *ingestion* chain over the source PDFs.
`extract` is cached on each file's content hash and will skip unchanged
documents, but `gate` and `facts` call cloud models on every document every
time — `facts.py` keeps no response cache. On a 55-document case that is a real
bill. You want this only when the extraction itself changed.

Neither touches `raw/`. The source documents are never modified.
"""
from __future__ import annotations

import argparse
import logging
import shutil
import subprocess
import sys
from pathlib import Path

from investigator import config
from investigator.run_case import run_case

log = logging.getLogger(__name__)

DEFAULT_CASE = "private"


def _already_running() -> str | None:
    """A stage still in flight, or None. Two runs would fight over the GPU."""
    out = subprocess.run(
        ["pgrep", "-af", "investigator.(orchestrator|discover)"],
        capture_output=True, text=True, check=False,
    )
    for line in out.stdout.splitlines():
        if "pgrep" not in line:
            return line.strip()
    return None


# What each scrub level removes. Ordered by what it costs to put back, which is
# the only distinction that matters when deciding how far to go.
#
#   analysis  — regenerated by local models. Free.
#   derived   — regenerated by gate + facts + distill + resolve + index, which
#               call cloud models on every document. Real money.
#   extracted — regenerated by the vision pass. The most expensive of all.
#
# `raw/` appears in none of them and is never touched.
_DERIVED = (
    "facts.jsonl", "actor_roles.jsonl", "role_ambiguities.jsonl",
    "coverage.jsonl", "distill_cache.jsonl", "persons.jsonl",
    "_persons_cache", "chunks.csv",
)


def _clear_analysis(paths: config.CasePaths) -> list[str]:
    """Remove regenerable analysis state. Never touches facts, persons or raw."""
    removed = []
    if paths.investigation_dir.exists():
        shutil.rmtree(paths.investigation_dir)
        removed.append(f"{paths.investigation_dir.name}/")
    for name in (paths.case_catalog_proposal.name, "obligations.authored.yaml.bak"):
        p = paths.case_dir / name
        if p.exists():
            p.unlink()
            removed.append(name)
    return removed


def _clear_derived(paths: config.CasePaths) -> list[str]:
    """Remove what the ingestion pipeline derives from the extracted text.

    Clearing rather than overwriting is what makes a rebuild mean "first time":
    `_write_case_jsonl` merges by document, so a stale row for a document that
    no longer exists would otherwise survive every rebuild.
    """
    removed = []
    for name in _DERIVED:
        p = paths.case_dir / name
        if not p.exists():
            continue
        shutil.rmtree(p) if p.is_dir() else p.unlink()
        removed.append(name + ("/" if p.is_dir() else ""))
    return removed


def _clear_extracted(paths: config.CasePaths) -> list[str]:
    """Remove the extracted transcripts, forcing a re-read of the sources."""
    d = paths.case_dir / "extracted"
    if not d.exists():
        return []
    shutil.rmtree(d)
    return ["extracted/"]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run one dossier end to end, locally.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--case-id", default=DEFAULT_CASE)
    parser.add_argument("--fresh", action="store_true",
                        help="discard findings, cache, digest, report and any proposal, "
                             "then redo the analysis (local models only — no cloud cost)")
    parser.add_argument("--rebuild", action="store_true",
                        help="also clear and regenerate the derived layer (facts, roles, "
                             "coverage, persons, chunks); gate and facts call cloud models "
                             "on every document (implies --fresh)")
    parser.add_argument("--reextract", action="store_true",
                        help="also clear extracted/, forcing the vision pass to re-read "
                             "every source document (implies --rebuild)")
    parser.add_argument("--raw-dir", type=Path, default=None,
                        help="source documents; defaults to <case>/raw for --rebuild")
    parser.add_argument("--no-local-llm", action="store_true",
                        help="deterministic verdicts only, no model adjudication")
    parser.add_argument("--outbound", action="store_true",
                        help="also write the gated outbound extract (refused for a real case)")
    parser.add_argument("--yes", "-y", action="store_true", help="skip the confirmation")
    args = parser.parse_args()

    busy = _already_running()
    if busy:
        log.error("a stage is already running — stop it first:\n  %s", busy)
        raise SystemExit(1)

    paths = config.CasePaths.for_case(args.case_id)
    if not paths.case_dir.exists():
        log.error("no such case: %s", paths.case_dir)
        raise SystemExit(1)

    raw_dir = args.raw_dir or (paths.case_dir / "raw")
    rebuild = args.rebuild or args.reextract
    fresh = args.fresh or rebuild

    # ---------- say what will happen, before doing any of it ----------
    print(f"\ncase        : {args.case_id}  ({paths.case_dir})")
    print(f"adjudication: {'local models' if not args.no_local_llm else 'deterministic only'}")
    if rebuild:
        n = sum(1 for p in raw_dir.rglob("*") if p.is_file()) if raw_dir.exists() else 0
        print(f"ingestion   : REBUILD from {raw_dir} ({n} source file(s))")
        if args.reextract:
            print("              extracted/ cleared — the VISION PASS re-reads every document")
        else:
            print("              extracted/ kept — extract is content-hash cached and skips")
        print("              gate and facts call cloud models on every document.")
    else:
        print("ingestion   : reuse existing facts, persons and chunks (no cloud calls)")
    print(f"analysis    : {'discard and redo' if fresh else 'resume from cache'}")
    if paths.case_catalog.exists():
        print(f"catalog     : {paths.case_catalog.name} (reviewed — discovery will not overwrite it)")
    else:
        print("catalog     : none yet — discovery will propose one and stop for review")
    print()

    if not args.yes and input("proceed? [y/N] ").strip().lower() not in ("y", "yes"):
        print("aborted")
        return

    if fresh:
        removed = _clear_analysis(paths)
        if rebuild:
            removed += _clear_derived(paths)
        if args.reextract:
            removed += _clear_extracted(paths)
        log.info("cleared: %s", ", ".join(removed) if removed else "nothing to clear")

    run_case(
        args.case_id,
        raw_dir=raw_dir if rebuild else None,
        skip_build=not rebuild,
        skip_discover=False,
        local_llm=not args.no_local_llm,
        outbound=args.outbound,
    )


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    try:
        main()
    except KeyboardInterrupt:
        # Safe by construction: every verdict is committed before the next
        # begins, so a re-run resumes from the cache having lost at most one.
        log.info("interrupted — re-run to resume from the cache")
        raise SystemExit(130) from None
