apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: capstone
    user: capstone
    secureJsonData:
      password: capstone
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
